services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - NEXT_PUBLIC_GATEWAY_URL=http://api-gateway:3005/proxy
    restart: unless-stopped
    volumes:
      - ./public:/app/public
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    name: api-gateway-network
    external: true